---
NONMEM_directory: /opt/NONMEM/nm75
NONMEM_version: '7.5'
PsN_version: 5.2.6
command_line: /usr/local/bin/execute -model_dir_name -nm_output=xml,ext,cov,cor,coi,phi,shk
  xgxr032.mod
common_options:
  abort_on_fail: 0
  accepted_ofv_difference: 0.5
  add_retries: 0
  always_datafile_in_nmrun: 0
  check_nmtran: '1'
  clean: 1
  compress: 0
  condition_number_limit: 1000
  correlation_limit: 0.85
  crash_restarts: '0'
  debug_rmd: 0
  degree: 0.1
  directory: /data/home/philipde/wdirs/NMsim/inst/examples/nonmem/xgxr032.dir1/
  display_iterations: '1'
  handle_crashes: 1
  handle_msfo: 0
  html: 0
  large_omega_cv_limit: 0.8
  large_sigma_cv_limit: 0.8
  large_theta_cv_limit: 0.5
  last_est_complete: 0
  lsf_sleep: 3
  min_retries: 0
  missing_data_token: '-99'
  model_subdir: 0
  near_bound_sign_digits: 2
  near_zero_boundary_limit: 0.01
  nice: 19
  nm_output: xml,ext,cov,cor,coi,phi,shk
  nm_version: default
  nmfe: '1'
  nmqual: '0'
  nodes: 0
  pdf: 1
  picky: 0
  prepend_model_file_name: 0
  quick_summarize: 0
  retries: 0
  rmarkdown: 1
  rplots: 0
  run_on_lsf: 0
  run_on_sge: 0
  run_on_slurm: 0
  run_on_torque: 0
  run_on_ud: 0
  run_on_zink: 0
  seed: 680401
  send_email: 0
  sge_prepend_flags: -V
  shrinkage: 0
  sign_digits_off_diagonals: 2
  significant_digits_accept: 0
  so: 0
  template_directory_rplots: /usr/local/share/perl/5.26.1/PsN_5_2_6/R-scripts
  template_file_rplots: execute_default.Rmd
  threads: '5'
  tweak_inits: 1
  verbose: 0
  zip: 0
copied_files:
- xgxr032.lst
- xgxr032.ext
- xgxr032.cov
- xgxr032.cor
- xgxr032.coi
- xgxr032.phi
- xgxr032.shk
- xgxr032.xml
- xgxr032_res.txt
- xgxr032_etas.txt
- xgxr032.msf
- xgxr032_ETAS.msf
- xgxr032_RMAT.msf
- xgxr032_SMAT.msf
finish_time: 2023-12-31 22:19:26
model_files:
- /data/home/philipde/wdirs/NMsim/inst/examples/nonmem/xgxr032.mod
start_time: 2023-12-31 22:15:37
tool_name: execute
tool_options:
  copy_data: 1
  prepend_options_to_lst: 0
  tail_output: 0
