##' Read simulation results based on NMsim's track of model runs
##' @param x Path to the simulation-specific rds file generated by NMsim,
##'   typically called `NMsim_MetaData.rds`. Can also be a table of simulation
##'   runs as stored in `rds` files by `NMsim`. The latter should almost never
##'   be used.
##' @param wait If simulations seem to not be done yet, wait for them to finish?
##'   If not, an error will be thrown. If you choose to wait, the risk is
##'   results never come. `NMreadSim` will be waiting for an `lst` file. If
##'   Nonmem fails, it will normally generate an `lst` file. But if `NMTRAN`
##'   fails (checks of control stream prior to running Nonmem), the `lst` file
##'   is not generated. Default is not to wait.
##' @param quiet Turn off some messages about what is going on? Default is to
##'   report the messages.
##' @param check.time If found, check whether `fst` file modification time is
##'   newer than `rds` file. The `fst` is generated based on information in
##'   `rds`, but notice that some systems don't preserve the file modification
##'   times. Becasue of that, `check.time` is `FALSE` by default.
##' @param dir.sims By default, `NMreadSim` will use information about the
##'   relative path from the results table file (`_MetaData.rds`) to the Nonmem
##'   simulation results. If these paths have changed, or for other reasons this
##'   doesn't work, you can use the `dir.sims` argument to specify where to find
##'   the Nonmem simulation results. If an `.fst` file was already generated and
##'   is found next to the `_MetaData.rds`, the path to the Nonmem simulation
##'   results is not used.
##' @param progress Track progress? Default is `TRUE` if `quiet` is FALSE and
##'   more than one model is being read. The progress tracking is based on the
##'   number of models completed/read, not the status of the individual models.
##' @param skip.missing Skip models where results are not available? Default is
##'   `FALSE` meaning an error will be thrown if one or more models do not have
##'   completed results.
##' @param rm.tmp If results are read successfully, remove temporary simulation
##'   results files? This can be useful after a script is developed and
##'   intermediate debugging information is not needed. It cleans up and saves
##'   significant disk space.
##' @param carry.out Variables from input data that should be included in
##'   results. This feature is only available if `NMsim()` was called with the
##'   `table.vars` argument. Also, it will only be used when reading results
##'   from output tables. To save time and disk space, `NMreadSim()` will store
##'   compressed `.fst` files, and when these are subsequently read by
##'   `NMreadSim()` `carry.out` is not used. To re-read the output tables and
##'   regenerate the `.fst` file, use `reread.tmp=TRUE`.
##' @param reread.tmp Force rereading of Nonmem results (if available) rather
##'   than using compressed results. Notice, if you are changing carry.out
##'   comparing to when compressed results were generated by `NMreadSim()`
##'   (possibly called by `NMsim()`), you will need `reread.tmp=TRUE`.
##' @param as.fun The default is to return data as a data.frame. Pass a function
##'   (say `tibble::as_tibble`) in as.fun to convert to something else. If
##'   data.tables are wanted, use as.fun="data.table". The default can be
##'   configured using NMdataConf.
##' @return A data set of class defined by as.fun
##' @import NMdata
##' @import data.table
##' @import fst
##' @importFrom xfun relative_path
##' @export



NMreadSim <- function(x,check.time=FALSE,dir.sims,wait=FALSE,quiet=FALSE,progress,skip.missing=FALSE,rm.tmp=FALSE,carry.out=NULL,reread.tmp=FALSE,as.fun){

  #### Section start: Dummy variables, only not to get NOTE's in pacakge checks ####
  
  . <- NULL
  fnExt <- NULL
  isChar <- NULL
  is.fst <- NULL
  is.lst <- NULL
  is.rds <- NULL
  is.res <- NULL
  is.simRes <- NULL
  is.simModTab <- NULL
  is.ModTab <- NULL
  Ix <- NULL
  method.read <- NULL
  model.sim <- NULL
  nmout <- NULL
  path.sim.lst <- NULL
  pathResFromSims <- NULL
  run.sim <- NULL
  x.class <- NULL

  ### Section end: Dummy variables, only not to get NOTE's in pacakge checks
  
  if(missing(dir.sims)) dir.sims <- NULL
  if(missing(as.fun)) as.fun <- NULL
  as.fun <- NMdata:::NMdataDecideOption("as.fun",as.fun)
  if(missing(progress)) progress <- NULL
  
  if(is.data.frame(x)) x <- list(x)
  ### recognized formats:
  ## NMsimRes - return x

  ## NMSimModels - read results in tab

  ## path to rds - read rds, then fst or lst
  

  if(length(x)==0) {
    message("No elementes in x. Returning NULL.")
    return(NULL)
  }

  
  ### determining file type to select processing method    
  ## dt.x <- data.table(is.rds=unlist(lapply(x,function(x)is.character(x)&&fnExtension(x)=="rds")))
  
  dt.x <- data.table(Ix=1:length(x))[
   ,method.read := NA_character_
  ]
  
  dt.x[is.simRes,method.read := "simres"]
  
  dt.x[,isChar:=unlist(lapply(x,is.character))]
  dt.x[isChar==TRUE,x.class:="char"]
  dt.x[x.class=="char"
      ,fnExt:=tolower(fnExtension(x))
       ]
  ## dt.x[,is.fst:=unlist(lapply(x,function(x)is.character(x)&&fnExtension(x)=="fst"))]
  
  ### is.simRes if it has already been read and collected by NMreadSim
  dt.x[,is.simRes:=unlist(lapply(x,is.NMsimRes))]
  
  dt.x[is.simRes==TRUE,method.read := "simres"]

  ### forcing reread of nonmem output tables
  if(reread.tmp){
    Irs <- dt.x[method.read=="simres",Ix]

    x <- lapply(1:length(x),function(i){
      if(!i%in%Irs) return(x)
      mt <- modTab(x[i])
      if(nrow(mt)) return(mt)
      
    })
    
    dt.x[Irs,method.read := "modtab"]
  }

  dt.x[,is.simModTab:=unlist(lapply(x,is.NMsimModTab))]
  
  if(dt.x[,any(!is.na(fnExt)&fnExt=="fst")]){
    if(!quiet ){
      message("Reading results from `.fst` file directly.\nPlease read the `_MetaData.rds` file instead to preserve model-related information.")
    }    
  }
  
  dt.x[is.na(method.read) & fnExt=="fst",method.read := "simres"]


  #### todo: message about limitations of reread.tmp and carry.out, depending on simtmp availability.

  

  dt.x[is.simModTab,method.read := "modtab"]
  dt.x[is.na(method.read) & fnExt=="rds",method.read := "modtab"]

  dt.x[is.na(method.read) & fnExt=="lst",method.read := "lst"]

  if(dt.x[,any(is.na(method.read))]){
    stop("Not all objects in `x` recognized by NMreadSim. They should be either (normally) paths to `rds` files or (mostly for programming) tables of simulation model information.")    
  }
  
  if(dt.x[,any(method.read=="lst")]){
    stop("`lst` (Nonmem output control stream) files found in `x`. NMreadSim() does not read those, and it is not recommended to read simulation results from those directly. Please use `rds` files generated by `NMsim()` because they contain more information. If you need to read `lst` files from earlier NMsim versions, please use NMdata::NMscanData() or NMdata::NMscanMultiple().")
  }

  
  ###### Reading results
  ## res.all <- NULL
  res.simRes <- NULL
  res.modTab <- NULL
  
  if(sum(dt.x$method.read=="simres")){
    res.simRes <- NMreadSimRes(x[dt.x[,method.read=="simres"]])
  }
  
  if(sum(dt.x$method.read=="modtab")){
    
    res.modTab <- NMreadSimModTab(x[dt.x[,method.read=="modtab"]],
                                  check.time=check.time,
                                  dir.sims=dir.sims,wait=wait,quiet=quiet,
                                  progress=progress,
                                  ## fast.tables=fast.tables,
                                  carry.out=carry.out,
                                  skip.missing=skip.missing,
                                  read.fst=!reread.tmp
                                  )

  }

  res.all <- rbind(res.simRes,res.modTab,fill=TRUE)  
  
  if("nmout"%in%colnames(res.all) && is.logical(res.all$nmout)){
    res.all[,nmout:=NULL]
  }

  ## attributes(res.all)$NMsimModTab
  if(rm.tmp){
    
    ## modtab <- attributes(res.all)$NMsimModTab
    modtab <- modTab(res.all)
    if(!is.null(modtab)){
      dirs.tmp <- unique(modtab[,file.path(dirname(x),modtab$pathSimsFromRes,model.sim)])
      if(length(dirs.tmp)){
        for (dir in dirs.tmp){
          if(dir.exists(dir)){
            unlink(dir,recursive=TRUE)
          }
        }
      }
    }   
  }

  
  res.all.modtab <- modTab(res.all)
  res.all <- as.fun(res.all)
  addClass(res.all,"NMsimRes")
  if(!is.null(res.all.modtab)){
    setattr(res.all,"NMsimModTab",res.all.modtab)
  }
  return(res.all)
}




